// Test generated by RoostGPT for test wordhunter using AI Type Open AI and AI Model gpt-4

package gq.niweera.wordhound.controller;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotEquals;

@RunWith(SpringRunner.class)
@SpringBootTest
public class BasicErrorController_getErrorPath_b49ea0b663_Test {

    private BasicErrorController basicErrorController;
    private static final String ERROR_PATH = "/error";

    @Before
    public void setup() {
        basicErrorController = new BasicErrorController();
    }

    @Test
    public void testGetErrorPath() {
        String result = basicErrorController.getErrorPath();
        assertEquals(ERROR_PATH, result);
    }

    @Test
    public void testGetErrorPathFailure() {
        String result = basicErrorController.getErrorPath();
        assertNotEquals("/wrongPath", result);
    }
}
